# Generated by Django 5.1.6 on 2026-03-01 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0014_alter_subtitle_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='b2_status',
            field=models.CharField(blank=True, db_index=True, help_text='B2 upload status: pending/running/success/fail. Null when B2 storage is not used.', max_length=20, null=True),
        ),
    ]
